### ISSUE TITLE
Use `currentColor` on Spoiler component instead

### ISSUE THREAD

**Issue by nndda** [nndda/itchio-css#4]
```css
.custom-hd:not(:hover) {
  color: currentColor;
  background: currentColor;
}
```
Maybe doesn't even need the `color` property
